apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::394445330613:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::394445330613:role/eksctl-simple-jwt-apii-nodegroup-NodeInstanceRole-2KVWS7PQMS34
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-19T21:09:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1222"
  uid: 8b09a956-4615-4972-bf8a-d4fe7cf3e888
